CREATE TABLE boxes (id INT AUTO_INCREMENT PRIMARY KEY,
barcode BIGINT NOT NULL,
title VARCHAR(255) NOT NULL);

CREATE TABLE documents (id INT AUTO_INCREMENT PRIMARY KEY,
barcode BIGINT NOT NULL,
title VARCHAR(255) NOT NULL,
box_id INT);